"""Excel import parsing and template generation for E-IZICUT.

Supports two workbook formats:
1. LEGACY (the user's existing file): sheets named "TAHUN 2025"/"TAHUN 2026",
   personnel grouped into sections separated by repeated header rows. Satfung is
   derived from the section leader's Jabatan. Columns hold only dates.
2. TEMPLATE (generated by /api/template): flat rows with an explicit SATFUNG
   column and paired "ALASAN ..." reason columns.
"""

import io
import re
from datetime import datetime, date

from openpyxl import load_workbook, Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

# Canonical leave categories.
LEAVE_TYPES = [
    "IZIN",
    "EMERGENCY",
    "CUTI_TAHUNAN",
    "CUTI_BEROBAT",
    "CUTI_IBADAH_UMROH",
    "CUTI_IBADAH_HAJI",
    "CUTI_IBADAH_LAINNYA",
]

LEAVE_LABELS = {
    "IZIN": "Izin",
    "EMERGENCY": "Izin Emergency",
    "CUTI_TAHUNAN": "Cuti Tahunan",
    "CUTI_BEROBAT": "Cuti Berobat",
    "CUTI_IBADAH_UMROH": "Cuti Ibadah Umroh",
    "CUTI_IBADAH_HAJI": "Cuti Ibadah Haji",
    "CUTI_IBADAH_LAINNYA": "Cuti Ibadah Lainnya",
}


def _norm(v):
    if v is None:
        return ""
    return str(v).strip()


def _parse_date(v):
    """Return ISO date string (YYYY-MM-DD) or None."""
    if v is None or v == "":
        return None
    if isinstance(v, datetime):
        return v.date().isoformat()
    if isinstance(v, date):
        return v.isoformat()
    s = str(v).strip()
    if not s:
        return None
    # Try common formats.
    fmts = ["%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y", "%m/%d/%Y", "%d %B %Y", "%d %b %Y",
            "%Y/%m/%d", "%d.%m.%Y"]
    for f in fmts:
        try:
            return datetime.strptime(s, f).date().isoformat()
        except ValueError:
            continue
    return s  # keep raw text if unparseable


def _year_from_sheet(title):
    m = re.search(r"(20\d{2})", title or "")
    return int(m.group(1)) if m else None


def derive_satfung(jabatan):
    """Derive a clean Satfung label from a leader's Jabatan string."""
    j = (jabatan or "").upper().strip()
    j = re.sub(r"\s+", " ", j)
    if not j:
        return "LAINNYA"
    if "KAPOLRES" in j or "WAKAPOLRES" in j:
        return "PIMPINAN"
    # strip acting prefixes
    for p in ("PS.", "PS ", "PLT.", "PLT ", "PLH.", "PLH ", "PJ.", "PJ "):
        if j.startswith(p):
            j = j[len(p):].strip()
    mapping = [
        ("KAPOLSEK", "POLSEK"),
        ("KABAG", "BAG"),
        ("KASAT", "SAT"),
        ("KASIDOKKES", "SIDOKKES"),
        ("KASIPROPAM", "SIPROPAM"),
        ("KASIHUMAS", "SIHUMAS"),
        ("KASIWAS", "SIWAS"),
        ("KASIKUM", "SIKUM"),
        ("KASIKEU", "SIKEU"),
        ("KASI TIK", "TIK"),
        ("KASI ", "SI "),
        ("KASI", "SI"),
        ("KA SPKT", "SPKT"),
        ("KA SIUM", "SIUM"),
        ("KA ", ""),
    ]
    for pre, rep in mapping:
        if j.startswith(pre):
            return (rep + j[len(pre):]).strip()
    return j


def _make_leaves(row_map):
    """row_map: dict of canonical field -> (date_value, reason_value)."""
    leaves = []
    for jenis, entries in row_map.items():
        for tanggal_raw, alasan in entries:
            iso = _parse_date(tanggal_raw)
            if iso:
                leaves.append({
                    "jenis": jenis,
                    "tanggal": iso,
                    "alasan": _norm(alasan),
                    "source": "excel",
                })
    return leaves


def _is_header(row):
    return _norm(row[2]).lower() == "nama" and _norm(row[3]).lower() == "pangkat"


def _is_template_header(row):
    joined = " ".join(_norm(c).upper() for c in row)
    return "SATFUNG" in joined and "NAMA" in joined and "NRP" in joined


def parse_workbook(data: bytes):
    """Return list of personnel dicts: {nrp, nama, pangkat, jabatan, satfung,
    tahun, order, leaves:[...]}. Raises ValueError on bad input."""
    wb = load_workbook(io.BytesIO(data), read_only=True, data_only=True)
    result = []
    for ws in wb.worksheets:
        year = _year_from_sheet(ws.title) or datetime.now().year
        rows = list(ws.iter_rows(values_only=True))
        # pad rows to at least 40 cols to avoid index errors
        rows = [list(r) + [None] * (40 - len(r)) if len(r) < 40 else list(r) for r in rows]

        # Detect template (flat) format via a SATFUNG header anywhere.
        template_hdr_idx = None
        for i, r in enumerate(rows):
            if _is_template_header(r):
                template_hdr_idx = i
                break

        if template_hdr_idx is not None:
            result.extend(_parse_template(rows, template_hdr_idx, year))
        else:
            result.extend(_parse_legacy(rows, year))
    return result


def _parse_template(rows, hdr_idx, year):
    header = [_norm(c).upper() for c in rows[hdr_idx]]
    idx = {}
    for i, h in enumerate(header):
        if h:
            idx[h] = i

    def col(*names):
        for n in names:
            if n in idx:
                return idx[n]
        return None

    c_nama = col("NAMA")
    c_pangkat = col("PANGKAT")
    c_nrp = col("NRP/NIP", "NRP", "NIP")
    c_jab = col("JABATAN")
    c_sat = col("SATFUNG", "SATKER", "UNIT")

    # date/reason pairs
    pairs = [
        ("IZIN", ["IJIN 1", "IZIN 1", "IJIN", "IZIN"], ["ALASAN IJIN 1", "ALASAN IZIN 1", "ALASAN IZIN"]),
        ("IZIN", ["IJIN 2", "IZIN 2"], ["ALASAN IJIN 2", "ALASAN IZIN 2"]),
        ("IZIN", ["IJIN 3", "IZIN 3"], ["ALASAN IJIN 3", "ALASAN IZIN 3"]),
        ("IZIN", ["IJIN 4", "IZIN 4"], ["ALASAN IJIN 4", "ALASAN IZIN 4"]),
        ("EMERGENCY", ["IJIN EMERGENCY", "IZIN EMERGENCY", "EMERGENCY"], ["ALASAN EMERGENCY"]),
        ("CUTI_TAHUNAN", ["CUTI TAHUNAN", "CUTI"], ["ALASAN CUTI TAHUNAN", "ALASAN CUTI"]),
        ("CUTI_BEROBAT", ["CUTI BEROBAT"], ["ALASAN CUTI BEROBAT", "ALASAN BEROBAT"]),
        ("CUTI_IBADAH_UMROH", ["CUTI IBADAH UMROH", "UMROH"], ["ALASAN UMROH", "ALASAN CUTI IBADAH UMROH"]),
        ("CUTI_IBADAH_HAJI", ["CUTI IBADAH HAJI", "HAJI"], ["ALASAN HAJI", "ALASAN CUTI IBADAH HAJI"]),
        ("CUTI_IBADAH_LAINNYA", ["CUTI IBADAH LAINNYA", "CUTI IBADAH"], ["ALASAN CUTI IBADAH LAINNYA", "ALASAN IBADAH"]),
    ]

    out = []
    order = 0
    for r in rows[hdr_idx + 1:]:
        nama = _norm(r[c_nama]) if c_nama is not None else ""
        if not nama or nama.lower() == "nama":
            continue
        pangkat = _norm(r[c_pangkat]) if c_pangkat is not None else ""
        if not pangkat and not (c_nrp is not None and _norm(r[c_nrp])):
            continue
        row_map = {}
        for jenis, dcols, rcols in pairs:
            dc = next((idx[c] for c in dcols if c in idx), None)
            rc = next((idx[c] for c in rcols if c in idx), None)
            if dc is None:
                continue
            dv = r[dc]
            rv = r[rc] if rc is not None else None
            if _parse_date(dv):
                row_map.setdefault(jenis, []).append((dv, rv))
        order += 1
        out.append({
            "nrp": _norm(r[c_nrp]) if c_nrp is not None else "",
            "nama": nama,
            "pangkat": pangkat,
            "jabatan": _norm(r[c_jab]) if c_jab is not None else "",
            "satfung": (_norm(r[c_sat]).upper() if c_sat is not None and _norm(r[c_sat]) else "LAINNYA"),
            "tahun": year,
            "order": order,
            "leaves": _make_leaves(row_map),
        })
    return out


def _as_int(v):
    try:
        return int(float(v))
    except (TypeError, ValueError):
        return None


def _detect_counter_col(members):
    """Pick the column (0 = col A "No", 1 = col B) that behaves as the
    per-satfung counter, i.e. the one that resets to 1 most often. Sections
    are separated by these resets regardless of header rows."""
    best_col, best_resets = None, -1
    for col in (0, 1):
        resets = 0
        prev = None
        for m in members:
            val = _as_int(m[col])
            if val is None:
                continue
            if prev is not None and val <= prev:
                resets += 1
            prev = val
        if resets > best_resets:
            best_resets = resets
            best_col = col
    return best_col if best_resets > 0 else None


def _parse_legacy(rows, year):
    """Section-based parse of the original file layout. Works for sheets with
    repeated header rows AND sheets that only reset a row-number column."""
    members = []
    for r in rows:
        if _is_header(r):
            continue
        nama = _norm(r[2])
        pangkat = _norm(r[3])
        if nama and nama.lower() != "nama" and (pangkat or _norm(r[4])):
            members.append(r)

    counter_col = _detect_counter_col(members)

    # Group members into sections using the resetting counter column.
    sections = []
    current = []
    prev = None
    for m in members:
        val = _as_int(m[counter_col]) if counter_col is not None else None
        is_new = counter_col is not None and val is not None and prev is not None and val <= prev
        if is_new and current:
            sections.append(current)
            current = []
        current.append(m)
        if val is not None:
            prev = val
    if current:
        sections.append(current)

    out = []
    order = 0
    for sec in sections:
        leader_jab = next((_norm(m[5]) for m in sec if _norm(m[5])), "")
        satfung = derive_satfung(leader_jab)
        for m in sec:
            order += 1
            row_map = {
                "IZIN": [(m[6], None), (m[7], None), (m[8], None), (m[9], None)],
                "EMERGENCY": [(m[10], None)],
                "CUTI_TAHUNAN": [(m[11], None)],
                "CUTI_BEROBAT": [(m[12], None)],
                "CUTI_IBADAH_LAINNYA": [(m[13], None)],
            }
            out.append({
                "nrp": _norm(m[4]),
                "nama": _norm(m[2]),
                "pangkat": _norm(m[3]),
                "jabatan": _norm(m[5]),
                "satfung": satfung,
                "tahun": year,
                "order": order,
                "leaves": _make_leaves(row_map),
            })
    return out


def build_template(satfung_list=None):
    """Generate an .xlsx template with explicit SATFUNG + reason columns."""
    wb = Workbook()
    gold = "D4AF37"
    header_fill = PatternFill("solid", fgColor="1E1E1E")
    header_font = Font(bold=True, color=gold, size=11)
    title_font = Font(bold=True, color=gold, size=14)
    thin = Side(style="thin", color="BFBFBF")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    center = Alignment(horizontal="center", vertical="center", wrap_text=True)

    headers = [
        "No", "Nama", "Pangkat", "NRP/NIP", "Satfung", "Jabatan",
        "IJIN 1", "ALASAN IJIN 1", "IJIN 2", "ALASAN IJIN 2",
        "IJIN 3", "ALASAN IJIN 3", "IJIN 4", "ALASAN IJIN 4",
        "IJIN EMERGENCY", "ALASAN EMERGENCY",
        "CUTI TAHUNAN", "ALASAN CUTI TAHUNAN",
        "CUTI BEROBAT", "ALASAN CUTI BEROBAT",
        "CUTI IBADAH UMROH", "ALASAN UMROH",
        "CUTI IBADAH HAJI", "ALASAN HAJI",
        "CUTI IBADAH LAINNYA", "ALASAN CUTI IBADAH LAINNYA",
    ]

    for year in (datetime.now().year, datetime.now().year + 1):
        ws = wb.create_sheet(title=f"TAHUN {year}")
        ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(headers))
        tcell = ws.cell(row=1, column=1, value=f"DATA IJIN CUTI PERSONIL POLRES MIMIKA {year}")
        tcell.font = title_font
        tcell.alignment = Alignment(horizontal="center", vertical="center")
        ws.cell(row=2, column=1, value="Format tanggal: DD-MM-YYYY. Kolom ALASAN diisi manual. Satfung wajib diisi (contoh: BAG SDM, SAT LANTAS, POLSEK MIMIKA BARU).")
        for c, h in enumerate(headers, start=1):
            cell = ws.cell(row=3, column=c, value=h)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = center
            cell.border = border
        # example row
        example = ["1", "CONTOH NAMA, S.H.", "AIPTU", "88010123", "BAG SDM",
                   "BANUM SUBBAG DALPERS BAG SDM", "05-01-2026", "Acara keluarga",
                   "", "", "", "", "", "", "", "", "12-02-2026", "Cuti tahunan",
                   "", "", "", "", "", "", "", ""]
        for c, v in enumerate(example, start=1):
            ws.cell(row=4, column=c, value=v).border = border
        widths = [5, 30, 10, 12, 16, 30] + [16, 24] * 10
        for i, w in enumerate(widths, start=1):
            ws.column_dimensions[chr(64 + i) if i <= 26 else "A" + chr(64 + i - 26)].width = w
        ws.freeze_panes = "A4"

    # remove default sheet
    if "Sheet" in wb.sheetnames:
        del wb["Sheet"]
    bio = io.BytesIO()
    wb.save(bio)
    bio.seek(0)
    return bio.read()
